/* This file automatically generated by configure.  */

#define PACKAGE "bc"
#define VERSION "nb1.0"
#define BC_COPYRIGHT "Copyright (C) 1991-1994, 1997, 2000, 2012-2017 "\
        "Free Software Foundation, Inc.\n"\
        "Copyright (C) 2004, 2005, 2016-2017 Philip A. Nelson"
#define QUIET

#define HAVE_SETVBUF
